spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}cb6680c147b443e771529b3e387e436d1a333302ac21e1662a89b603b8716002'
token:
  expiration_time: 864000000
  secret: user_token_native_application

gateway:
  ip: 192.168.0.8
